import { createFileRoute, Link } from "@tanstack/react-router";
import { ShieldAlert, ArrowRight } from "lucide-react";
import { AuthLayout } from "./login";

export const Route = createFileRoute("/signup")({
  component: SignupPage,
  head: () => ({ meta: [{ title: "Sign up — HR Management System" }] }),
});

function SignupPage() {
  return (
    <AuthLayout
      title="Self sign-up is disabled"
      subtitle="Accounts are provisioned by your HR team."
    >
      <div className="rounded-2xl border border-primary/20 bg-primary/5 p-5 flex items-start gap-3">
        <ShieldAlert className="w-5 h-5 text-primary mt-0.5" />
        <div className="text-sm">
          <div className="font-semibold">Only HR & Admins can create employees.</div>
          <div className="text-muted-foreground mt-1">
            Your Login ID (e.g. <span className="font-mono">OIJODO20220001</span>) and a temporary password are
            generated by the system when your profile is created. Ask your HR officer for your credentials, then
            sign in and change your password from your profile.
          </div>
        </div>
      </div>

      <Link
        to="/login"
        className="mt-6 w-full py-3 rounded-xl bg-gradient-primary text-primary-foreground font-semibold shadow-elegant hover:shadow-glow transition-all flex items-center justify-center gap-2"
      >
        Go to sign in <ArrowRight className="w-4 h-4" />
      </Link>
    </AuthLayout>
  );
}
