/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPayrollRouteImport } from './routes/app.payroll'
import { Route as AppLeaveRouteImport } from './routes/app.leave'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppAttendanceRouteImport } from './routes/app.attendance'
import { Route as AppAdminPayrollRouteImport } from './routes/app.admin.payroll'
import { Route as AppAdminLeaveRouteImport } from './routes/app.admin.leave'
import { Route as AppAdminEmployeesRouteImport } from './routes/app.admin.employees'
import { Route as AppAdminAuditRouteImport } from './routes/app.admin.audit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaveRoute = AppLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPayrollRoute = AppAdminPayrollRouteImport.update({
  id: '/admin/payroll',
  path: '/admin/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminLeaveRoute = AppAdminLeaveRouteImport.update({
  id: '/admin/leave',
  path: '/admin/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminEmployeesRoute = AppAdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/employees': typeof AppAdminEmployeesRoute
  '/app/admin/leave': typeof AppAdminLeaveRoute
  '/app/admin/payroll': typeof AppAdminPayrollRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/profile': typeof AppProfileRoute
  '/app': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/employees': typeof AppAdminEmployeesRoute
  '/app/admin/leave': typeof AppAdminLeaveRoute
  '/app/admin/payroll': typeof AppAdminPayrollRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/attendance': typeof AppAttendanceRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/leave': typeof AppLeaveRoute
  '/app/payroll': typeof AppPayrollRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/admin/audit': typeof AppAdminAuditRoute
  '/app/admin/employees': typeof AppAdminEmployeesRoute
  '/app/admin/leave': typeof AppAdminLeaveRoute
  '/app/admin/payroll': typeof AppAdminPayrollRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/attendance'
    | '/app/dashboard'
    | '/app/leave'
    | '/app/payroll'
    | '/app/profile'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/employees'
    | '/app/admin/leave'
    | '/app/admin/payroll'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/attendance'
    | '/app/dashboard'
    | '/app/leave'
    | '/app/payroll'
    | '/app/profile'
    | '/app'
    | '/app/admin/audit'
    | '/app/admin/employees'
    | '/app/admin/leave'
    | '/app/admin/payroll'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/attendance'
    | '/app/dashboard'
    | '/app/leave'
    | '/app/payroll'
    | '/app/profile'
    | '/app/'
    | '/app/admin/audit'
    | '/app/admin/employees'
    | '/app/admin/leave'
    | '/app/admin/payroll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/payroll': {
      id: '/app/payroll'
      path: '/payroll'
      fullPath: '/app/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leave': {
      id: '/app/leave'
      path: '/leave'
      fullPath: '/app/leave'
      preLoaderRoute: typeof AppLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/attendance': {
      id: '/app/attendance'
      path: '/attendance'
      fullPath: '/app/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/payroll': {
      id: '/app/admin/payroll'
      path: '/admin/payroll'
      fullPath: '/app/admin/payroll'
      preLoaderRoute: typeof AppAdminPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/leave': {
      id: '/app/admin/leave'
      path: '/admin/leave'
      fullPath: '/app/admin/leave'
      preLoaderRoute: typeof AppAdminLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/employees': {
      id: '/app/admin/employees'
      path: '/admin/employees'
      fullPath: '/app/admin/employees'
      preLoaderRoute: typeof AppAdminEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/audit': {
      id: '/app/admin/audit'
      path: '/admin/audit'
      fullPath: '/app/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeaveRoute: typeof AppLeaveRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminEmployeesRoute: typeof AppAdminEmployeesRoute
  AppAdminLeaveRoute: typeof AppAdminLeaveRoute
  AppAdminPayrollRoute: typeof AppAdminPayrollRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttendanceRoute: AppAttendanceRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeaveRoute: AppLeaveRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminEmployeesRoute: AppAdminEmployeesRoute,
  AppAdminLeaveRoute: AppAdminLeaveRoute,
  AppAdminPayrollRoute: AppAdminPayrollRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
